config/routes.rb
Rails.application.routes.draw do
  root to: 'logos#index'
  resources :logos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/logo.rb
class Logo < ApplicationRecord
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logos_controller.rb
class LogosController < ApplicationController
  before_action :set_logo, only: [:show, :edit, :update, :destroy]

  # GET /logos
  # GET /logos.json
  def index
    @logos = Logo.all
  end

  # GET /logos/1
  # GET /logos/1.json
  def show
  end

  # GET /logos/new
  def new
    @logo = Logo.new
  end

  # GET /logos/1/edit
  def edit
  end

  # POST /logos
  # POST /logos.json
  def create
    @logo = Logo.new(logo_params)

    respond_to do |format|
      if @logo.save
        format.html { redirect_to @logo, notice: 'Logo was successfully created.' }
        format.json { render :show, status: :created, location: @logo }
      else
        format.html { render :new }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logos/1
  # PATCH/PUT /logos/1.json
  def update
    respond_to do |format|
      if @logo.update(logo_params)
        format.html { redirect_to @logo, notice: 'Logo was successfully updated.' }
        format.json { render :show, status: :ok, location: @logo }
      else
        format.html { render :edit }
        format.json { render json: @logo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logos/1
  # DELETE /logos/1.json
  def destroy
    @logo.destroy
    respond_to do |format|
      format.html { redirect_to logos_url, notice: 'Logo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logo
      @logo = Logo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def logo_params
      params.require(:logo).permit(:title, :caption, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logos_helper.rb
module LogosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsGems</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logos/_form.html.erb
<%= form_with(model: logo, local: true) do |form| %>
  <% if logo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(logo.errors.count, "error") %> prohibited this logo from being saved:</h2>

      <ul>
      <% logo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_area :caption %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logos/edit.html.erb
<h1>Editing Logo</h1>

<%= render 'form', logo: @logo %>

<%= link_to 'Show', @logo %> |
<%= link_to 'Back', logos_path %>

app/views/logos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logos.each do |logo| %>
      <tr>
        <td><%= logo.title %></td>
        <td><%= logo.caption %></td>
        <td><%= link_to 'Show', logo %></td>
        <td><%= link_to 'Edit', edit_logo_path(logo) %></td>
        <td><%= link_to 'Destroy', logo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Logo', new_logo_path %>

app/views/logos/new.html.erb
<h1>New Logo</h1>

<%= render 'form', logo: @logo %>

<%= link_to 'Back', logos_path %>

app/views/logos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @logo.title %>
</p>

<%= image_tag(@logo.image) %>

<p>
  <strong>Caption:</strong>
  <%= @logo.caption %>
</p>

<%= link_to 'Edit', edit_logo_path(@logo) %> |
<%= link_to 'Back', logos_path %>